### ISSUE TITLE
connect to ROSBRIDGE from backend server

### ISSUE THREAD

**Issue by AmineKamrobotica** [RobotWebTools/ros2djs#99] opened 2022-06-14 15:29 UTC
i have multiple robots i establish the connection throw vpn .. i wanna make this dynamic so i installed my vpn server on my vps and its configuration . so the connection with rosbridge should happen from the server not from the client (front end).

i wrote a node js server like this 
![image](https://user-images.githubusercontent.com/91333642/173615667-73d93564-75ac-4c31-abcd-72208b650129.png)

but i got this response 
```
{....
        "idCounter": 0,
        "isConnected": false,
        "transportLibrary": "websocket",
        "transportOptions": {},
        "groovyCompatibility": true,
        "_maxListeners": 0,
        "_conf": {
            "maxListeners": 0
        }
...}
```
ps : rosbridge on my terminal record that a client establish a connection

i ask for a help or debate to resolve it thanks community

**Comment by MatthijsBurgh** [comment] 2022-06-14 17:04
What is the problem?

**Comment by AmineKamrobotica** [comment] 2022-06-15 09:30
when i send the object of connection (in my case the variable ros) throw axios request to the front side, it seems to me don't work to manage the connection event.
i recorded that the key isConnected is false  but when i establish the connection from the front it is true. 
{....
        "idCounter": 0,
        "isConnected": false,
        "transportLibrary": "websocket",       
...}

if there is any other idea to switch the connection between different ipadresses of rosbridge i'm interested to know because that's my problem.
thanks

**Comment by MatthijsBurgh** [comment] 2023-02-10 13:56
This really sounds like a `websocket` issue. I don't have the knowledge. As long as there is a connection possible from the machine ,where you have your ROS instance, either a browser or a node script, to the `rosbridge_server` machine. It should be an issue. For the connection  make sure the correct ports are open. As the issue is not related to `ros2djs` (and actually also not really to `roslibjs`), I am closing this.

**Closed as not planned by MatthijsBurgh** 2023-02-10 13:56 UTC
